# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1071, 722)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_11.addLayout(self.verticalLayout_4, 0, 3, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.DC = QtWidgets.QWidget()
        self.DC.setObjectName("DC")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.DC)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_17 = QtWidgets.QPushButton(self.DC)
        self.pushButton_17.setObjectName("pushButton_17")
        self.gridLayout_2.addWidget(self.pushButton_17, 5, 1, 1, 2)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.DC)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_3.addWidget(self.pushButton_2, 5, 0, 1, 2)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.DC)
        self.doubleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox.setMinimum(-15.0)
        self.doubleSpinBox.setMaximum(15.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout_3.addWidget(self.doubleSpinBox, 4, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.DC)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.DC)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_3.setSpacing(1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.DC)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.Speed = QtWidgets.QDial(self.DC)
        self.Speed.setObjectName("Speed")
        self.horizontalLayout_3.addWidget(self.Speed)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 1, 0, 2, 2)
        self.gridLayout_2.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_7 = QtWidgets.QLabel(self.DC)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 4, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.DC)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_5.addWidget(self.pushButton_4, 5, 0, 1, 2)
        self.label_8 = QtWidgets.QLabel(self.DC)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 0, 0, 1, 2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_5.setSpacing(1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_9 = QtWidgets.QLabel(self.DC)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_5.addWidget(self.label_9)
        self.Speed_3 = QtWidgets.QDial(self.DC)
        self.Speed_3.setObjectName("Speed_3")
        self.horizontalLayout_5.addWidget(self.Speed_3)
        self.gridLayout_5.addLayout(self.horizontalLayout_5, 1, 0, 2, 2)
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.DC)
        self.doubleSpinBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_3.setMinimum(-15.0)
        self.doubleSpinBox_3.setMaximum(15.0)
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.gridLayout_5.addWidget(self.doubleSpinBox_3, 4, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_5, 0, 2, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButton_3 = QtWidgets.QPushButton(self.DC)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_4.addWidget(self.pushButton_3, 5, 0, 1, 2)
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.DC)
        self.doubleSpinBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_2.setMinimum(-15.0)
        self.doubleSpinBox_2.setMaximum(15.0)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.gridLayout_4.addWidget(self.doubleSpinBox_2, 4, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.DC)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 4, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.DC)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 0, 0, 1, 2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_4.setSpacing(1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.DC)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.Speed_2 = QtWidgets.QDial(self.DC)
        self.Speed_2.setObjectName("Speed_2")
        self.horizontalLayout_4.addWidget(self.Speed_2)
        self.gridLayout_4.addLayout(self.horizontalLayout_4, 1, 0, 2, 2)
        self.gridLayout_2.addLayout(self.gridLayout_4, 0, 1, 1, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.pushButton_5 = QtWidgets.QPushButton(self.DC)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_6.addWidget(self.pushButton_5, 5, 0, 1, 2)
        self.doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(self.DC)
        self.doubleSpinBox_4.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_4.setMinimum(-15.0)
        self.doubleSpinBox_4.setMaximum(15.0)
        self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
        self.gridLayout_6.addWidget(self.doubleSpinBox_4, 4, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.DC)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_6.addWidget(self.label_10, 4, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.DC)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_6.addWidget(self.label_11, 0, 0, 1, 2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_6.setSpacing(1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_12 = QtWidgets.QLabel(self.DC)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_6.addWidget(self.label_12)
        self.Speed_4 = QtWidgets.QDial(self.DC)
        self.Speed_4.setObjectName("Speed_4")
        self.horizontalLayout_6.addWidget(self.Speed_4)
        self.gridLayout_6.addLayout(self.horizontalLayout_6, 1, 0, 2, 2)
        self.gridLayout_2.addLayout(self.gridLayout_6, 0, 3, 1, 1)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.pushButton_6 = QtWidgets.QPushButton(self.DC)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_7.addWidget(self.pushButton_6, 5, 0, 1, 2)
        self.doubleSpinBox_5 = QtWidgets.QDoubleSpinBox(self.DC)
        self.doubleSpinBox_5.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_5.setMinimum(-15.0)
        self.doubleSpinBox_5.setMaximum(15.0)
        self.doubleSpinBox_5.setObjectName("doubleSpinBox_5")
        self.gridLayout_7.addWidget(self.doubleSpinBox_5, 4, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.DC)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_7.addWidget(self.label_13, 4, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.DC)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_7.addWidget(self.label_14, 0, 0, 1, 2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_7.setSpacing(1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_15 = QtWidgets.QLabel(self.DC)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_7.addWidget(self.label_15)
        self.Speed_5 = QtWidgets.QDial(self.DC)
        self.Speed_5.setObjectName("Speed_5")
        self.horizontalLayout_7.addWidget(self.Speed_5)
        self.gridLayout_7.addLayout(self.horizontalLayout_7, 1, 0, 2, 2)
        self.gridLayout_2.addLayout(self.gridLayout_7, 1, 0, 1, 1)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.pushButton_7 = QtWidgets.QPushButton(self.DC)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_8.addWidget(self.pushButton_7, 5, 0, 1, 2)
        self.doubleSpinBox_6 = QtWidgets.QDoubleSpinBox(self.DC)
        self.doubleSpinBox_6.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_6.setMinimum(-15.0)
        self.doubleSpinBox_6.setMaximum(15.0)
        self.doubleSpinBox_6.setObjectName("doubleSpinBox_6")
        self.gridLayout_8.addWidget(self.doubleSpinBox_6, 4, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.DC)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_8.addWidget(self.label_16, 4, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.DC)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_8.addWidget(self.label_17, 0, 0, 1, 2)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_8.setSpacing(1)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_18 = QtWidgets.QLabel(self.DC)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_8.addWidget(self.label_18)
        self.Speed_6 = QtWidgets.QDial(self.DC)
        self.Speed_6.setObjectName("Speed_6")
        self.horizontalLayout_8.addWidget(self.Speed_6)
        self.gridLayout_8.addLayout(self.horizontalLayout_8, 1, 0, 2, 2)
        self.gridLayout_2.addLayout(self.gridLayout_8, 1, 1, 1, 1)
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.pushButton_8 = QtWidgets.QPushButton(self.DC)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_9.addWidget(self.pushButton_8, 5, 0, 1, 2)
        self.doubleSpinBox_7 = QtWidgets.QDoubleSpinBox(self.DC)
        self.doubleSpinBox_7.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_7.setMinimum(-15.0)
        self.doubleSpinBox_7.setMaximum(15.0)
        self.doubleSpinBox_7.setObjectName("doubleSpinBox_7")
        self.gridLayout_9.addWidget(self.doubleSpinBox_7, 4, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.DC)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_9.addWidget(self.label_19, 4, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.DC)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout_9.addWidget(self.label_20, 0, 0, 1, 2)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_9.setSpacing(1)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_21 = QtWidgets.QLabel(self.DC)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_9.addWidget(self.label_21)
        self.Speed_7 = QtWidgets.QDial(self.DC)
        self.Speed_7.setObjectName("Speed_7")
        self.horizontalLayout_9.addWidget(self.Speed_7)
        self.gridLayout_9.addLayout(self.horizontalLayout_9, 1, 0, 2, 2)
        self.gridLayout_2.addLayout(self.gridLayout_9, 1, 2, 1, 1)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_22 = QtWidgets.QLabel(self.DC)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.gridLayout_10.addWidget(self.label_22, 4, 0, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.DC)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_10.addWidget(self.pushButton_9, 5, 0, 1, 2)
        self.label_23 = QtWidgets.QLabel(self.DC)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.gridLayout_10.addWidget(self.label_23, 0, 0, 1, 2)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_10.setSpacing(1)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_24 = QtWidgets.QLabel(self.DC)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_10.addWidget(self.label_24)
        self.Speed_8 = QtWidgets.QDial(self.DC)
        self.Speed_8.setObjectName("Speed_8")
        self.horizontalLayout_10.addWidget(self.Speed_8)
        self.gridLayout_10.addLayout(self.horizontalLayout_10, 1, 0, 2, 2)
        self.doubleSpinBox_8 = QtWidgets.QDoubleSpinBox(self.DC)
        self.doubleSpinBox_8.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_8.setMinimum(-15.0)
        self.doubleSpinBox_8.setMaximum(15.0)
        self.doubleSpinBox_8.setObjectName("doubleSpinBox_8")
        self.gridLayout_10.addWidget(self.doubleSpinBox_8, 4, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_10, 1, 3, 1, 1)
        self.tabWidget.addTab(self.DC, "")
        self.SM = QtWidgets.QWidget()
        self.SM.setObjectName("SM")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.SM)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.textEdit = QtWidgets.QTextEdit(self.SM)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_12.addWidget(self.textEdit, 1, 1, 1, 3)
        self.lineEdit = QtWidgets.QLineEdit(self.SM)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_12.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.SM)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_12.addWidget(self.pushButton, 0, 3, 1, 1)
        self.tabWidget.addTab(self.SM, "")
        self.RP = QtWidgets.QWidget()
        self.RP.setObjectName("RP")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.RP)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.RP)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_24.addWidget(self.lineEdit_2, 0, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.RP)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_24.addWidget(self.progressBar, 1, 0, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.RP)
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_24.addWidget(self.pushButton_10, 0, 1, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.RP)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout_24.addWidget(self.tableWidget, 2, 0, 1, 2)
        self.pushButton_11 = QtWidgets.QPushButton(self.RP)
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout_24.addWidget(self.pushButton_11, 1, 1, 1, 1)
        self.tabWidget.addTab(self.RP, "")
        self.CONFIG = QtWidgets.QWidget()
        self.CONFIG.setObjectName("CONFIG")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.CONFIG)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setContentsMargins(30, -1, 30, -1)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_25 = QtWidgets.QLabel(self.CONFIG)
        self.label_25.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_25.setObjectName("label_25")
        self.gridLayout_13.addWidget(self.label_25, 0, 0, 1, 2)
        self.label_27 = QtWidgets.QLabel(self.CONFIG)
        self.label_27.setObjectName("label_27")
        self.gridLayout_13.addWidget(self.label_27, 2, 0, 1, 1)
        self.spinBox_2 = QtWidgets.QSpinBox(self.CONFIG)
        self.spinBox_2.setMaximum(10000)
        self.spinBox_2.setProperty("value", 2000)
        self.spinBox_2.setObjectName("spinBox_2")
        self.gridLayout_13.addWidget(self.spinBox_2, 2, 1, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.CONFIG)
        self.spinBox.setMaximum(20000)
        self.spinBox.setProperty("value", 1)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout_13.addWidget(self.spinBox, 1, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.CONFIG)
        self.label_26.setObjectName("label_26")
        self.gridLayout_13.addWidget(self.label_26, 1, 0, 1, 1)
        self.gridLayout_23.addLayout(self.gridLayout_13, 0, 0, 1, 1)
        self.gridLayout_16 = QtWidgets.QGridLayout()
        self.gridLayout_16.setContentsMargins(30, -1, 30, -1)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.label_31 = QtWidgets.QLabel(self.CONFIG)
        self.label_31.setObjectName("label_31")
        self.gridLayout_16.addWidget(self.label_31, 1, 0, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.CONFIG)
        self.label_32.setObjectName("label_32")
        self.gridLayout_16.addWidget(self.label_32, 2, 0, 1, 1)
        self.spinBox_5 = QtWidgets.QSpinBox(self.CONFIG)
        self.spinBox_5.setMaximum(20000)
        self.spinBox_5.setProperty("value", 1)
        self.spinBox_5.setObjectName("spinBox_5")
        self.gridLayout_16.addWidget(self.spinBox_5, 1, 1, 1, 1)
        self.spinBox_6 = QtWidgets.QSpinBox(self.CONFIG)
        self.spinBox_6.setMaximum(10000)
        self.spinBox_6.setProperty("value", 2000)
        self.spinBox_6.setObjectName("spinBox_6")
        self.gridLayout_16.addWidget(self.spinBox_6, 2, 1, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.CONFIG)
        self.label_33.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_33.setObjectName("label_33")
        self.gridLayout_16.addWidget(self.label_33, 0, 0, 1, 2)
        self.gridLayout_23.addLayout(self.gridLayout_16, 0, 1, 1, 1)
        self.gridLayout_19 = QtWidgets.QGridLayout()
        self.gridLayout_19.setContentsMargins(30, -1, 30, -1)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.spinBox_11 = QtWidgets.QSpinBox(self.CONFIG)
        self.spinBox_11.setMaximum(20000)
        self.spinBox_11.setProperty("value", 1)
        self.spinBox_11.setObjectName("spinBox_11")
        self.gridLayout_19.addWidget(self.spinBox_11, 1, 1, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.CONFIG)
        self.label_40.setObjectName("label_40")
        self.gridLayout_19.addWidget(self.label_40, 1, 0, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.CONFIG)
        self.label_42.setObjectName("label_42")
        self.gridLayout_19.addWidget(self.label_42, 2, 0, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.CONFIG)
        self.label_43.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_43.setObjectName("label_43")
        self.gridLayout_19.addWidget(self.label_43, 0, 0, 1, 2)
        self.spinBox_12 = QtWidgets.QSpinBox(self.CONFIG)
        self.spinBox_12.setMaximum(10000)
        self.spinBox_12.setProperty("value", 2000)
        self.spinBox_12.setObjectName("spinBox_12")
        self.gridLayout_19.addWidget(self.spinBox_12, 2, 1, 1, 1)
        self.gridLayout_23.addLayout(self.gridLayout_19, 2, 0, 1, 1)
        self.gridLayout_20 = QtWidgets.QGridLayout()
        self.gridLayout_20.setContentsMargins(30, -1, 30, -1)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.spinBox_14 = QtWidgets.QSpinBox(self.CONFIG)
        self.spinBox_14.setMaximum(10000)
        self.spinBox_14.setProperty("value", 2000)
        self.spinBox_14.setObjectName("spinBox_14")
        self.gridLayout_20.addWidget(self.spinBox_14, 2, 1, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.CONFIG)
        self.label_46.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_46.setObjectName("label_46")
        self.gridLayout_20.addWidget(self.label_46, 0, 0, 1, 2)
        self.spinBox_13 = QtWidgets.QSpinBox(self.CONFIG)
        self.spinBox_13.setMaximum(20000)
        self.spinBox_13.setProperty("value", 1)
        self.spinBox_13.setObjectName("spinBox_13")
        self.gridLayout_20.addWidget(self.spinBox_13, 1, 1, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.CONFIG)
        self.label_44.setObjectName("label_44")
        self.gridLayout_20.addWidget(self.label_44, 1, 0, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.CONFIG)
        self.label_45.setObjectName("label_45")
        self.gridLayout_20.addWidget(self.label_45, 2, 0, 1, 1)
        self.gridLayout_23.addLayout(self.gridLayout_20, 2, 1, 1, 1)
        self.gridLayout_17 = QtWidgets.QGridLayout()
        self.gridLayout_17.setContentsMargins(30, -1, 30, -1)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.spinBox_7 = QtWidgets.QSpinBox(self.CONFIG)
        self.spinBox_7.setMaximum(20000)
        self.spinBox_7.setProperty("value", 1)
        self.spinBox_7.setObjectName("spinBox_7")
        self.gridLayout_17.addWidget(self.spinBox_7, 1, 1, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.CONFIG)
        self.label_34.setObjectName("label_34")
        self.gridLayout_17.addWidget(self.label_34, 1, 0, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.CONFIG)
        self.label_35.setObjectName("label_35")
        self.gridLayout_17.addWidget(self.label_35, 2, 0, 1, 1)
        self.spinBox_8 = QtWidgets.QSpinBox(self.CONFIG)
        self.spinBox_8.setMaximum(10000)
        self.spinBox_8.setProperty("value", 2000)
        self.spinBox_8.setObjectName("spinBox_8")
        self.gridLayout_17.addWidget(self.spinBox_8, 2, 1, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.CONFIG)
        self.label_36.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_36.setObjectName("label_36")
        self.gridLayout_17.addWidget(self.label_36, 0, 0, 1, 2)
        self.gridLayout_23.addLayout(self.gridLayout_17, 0, 2, 1, 1)
        self.gridLayout_18 = QtWidgets.QGridLayout()
        self.gridLayout_18.setContentsMargins(30, -1, 30, -1)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.spinBox_9 = QtWidgets.QSpinBox(self.CONFIG)
        self.spinBox_9.setMaximum(20000)
        self.spinBox_9.setProperty("value", 1)
        self.spinBox_9.setObjectName("spinBox_9")
        self.gridLayout_18.addWidget(self.spinBox_9, 1, 1, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.CONFIG)
        self.label_37.setObjectName("label_37")
        self.gridLayout_18.addWidget(self.label_37, 1, 0, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.CONFIG)
        self.label_38.setObjectName("label_38")
        self.gridLayout_18.addWidget(self.label_38, 2, 0, 1, 1)
        self.spinBox_10 = QtWidgets.QSpinBox(self.CONFIG)
        self.spinBox_10.setMaximum(10000)
        self.spinBox_10.setProperty("value", 2000)
        self.spinBox_10.setObjectName("spinBox_10")
        self.gridLayout_18.addWidget(self.spinBox_10, 2, 1, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.CONFIG)
        self.label_39.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_39.setObjectName("label_39")
        self.gridLayout_18.addWidget(self.label_39, 0, 0, 1, 2)
        self.gridLayout_23.addLayout(self.gridLayout_18, 0, 3, 1, 1)
        self.gridLayout_21 = QtWidgets.QGridLayout()
        self.gridLayout_21.setContentsMargins(30, -1, 30, -1)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.label_48 = QtWidgets.QLabel(self.CONFIG)
        self.label_48.setObjectName("label_48")
        self.gridLayout_21.addWidget(self.label_48, 2, 0, 1, 1)
        self.spinBox_16 = QtWidgets.QSpinBox(self.CONFIG)
        self.spinBox_16.setMaximum(10000)
        self.spinBox_16.setProperty("value", 2000)
        self.spinBox_16.setObjectName("spinBox_16")
        self.gridLayout_21.addWidget(self.spinBox_16, 2, 1, 1, 1)
        self.spinBox_15 = QtWidgets.QSpinBox(self.CONFIG)
        self.spinBox_15.setMaximum(20000)
        self.spinBox_15.setProperty("value", 1)
        self.spinBox_15.setObjectName("spinBox_15")
        self.gridLayout_21.addWidget(self.spinBox_15, 1, 1, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.CONFIG)
        self.label_47.setObjectName("label_47")
        self.gridLayout_21.addWidget(self.label_47, 1, 0, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.CONFIG)
        self.label_49.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_49.setObjectName("label_49")
        self.gridLayout_21.addWidget(self.label_49, 0, 0, 1, 2)
        self.gridLayout_23.addLayout(self.gridLayout_21, 2, 2, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_5.addItem(spacerItem)
        self.frame = QtWidgets.QFrame(self.CONFIG)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_5.addWidget(self.frame)
        self.gridLayout_23.addLayout(self.verticalLayout_5, 3, 0, 1, 4)
        self.gridLayout_22 = QtWidgets.QGridLayout()
        self.gridLayout_22.setContentsMargins(30, -1, 30, -1)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.label_52 = QtWidgets.QLabel(self.CONFIG)
        self.label_52.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_52.setObjectName("label_52")
        self.gridLayout_22.addWidget(self.label_52, 0, 0, 1, 2)
        self.spinBox_18 = QtWidgets.QSpinBox(self.CONFIG)
        self.spinBox_18.setMaximum(10000)
        self.spinBox_18.setProperty("value", 2000)
        self.spinBox_18.setObjectName("spinBox_18")
        self.gridLayout_22.addWidget(self.spinBox_18, 2, 1, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.CONFIG)
        self.label_51.setObjectName("label_51")
        self.gridLayout_22.addWidget(self.label_51, 2, 0, 1, 1)
        self.spinBox_17 = QtWidgets.QSpinBox(self.CONFIG)
        self.spinBox_17.setMaximum(20000)
        self.spinBox_17.setProperty("value", 1)
        self.spinBox_17.setObjectName("spinBox_17")
        self.gridLayout_22.addWidget(self.spinBox_17, 1, 1, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.CONFIG)
        self.label_50.setObjectName("label_50")
        self.gridLayout_22.addWidget(self.label_50, 1, 0, 1, 1)
        self.gridLayout_23.addLayout(self.gridLayout_22, 2, 3, 1, 1)
        self.tabWidget.addTab(self.CONFIG, "")
        self.gridLayout_11.addWidget(self.tabWidget, 3, 0, 1, 1)
        self.SerialSelect = QtWidgets.QComboBox(self.centralwidget)
        self.SerialSelect.setObjectName("SerialSelect")
        self.gridLayout_11.addWidget(self.SerialSelect, 2, 0, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.centralwidget)
        self.label_41.setObjectName("label_41")
        self.gridLayout_11.addWidget(self.label_41, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1071, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionDirectControl = QtWidgets.QAction(MainWindow)
        self.actionDirectControl.setObjectName("actionDirectControl")
        self.actionRunProtocol = QtWidgets.QAction(MainWindow)
        self.actionRunProtocol.setObjectName("actionRunProtocol")
        self.actionSerial_responses = QtWidgets.QAction(MainWindow)
        self.actionSerial_responses.setObjectName("actionSerial_responses")
        self.actionSystem_configuration = QtWidgets.QAction(MainWindow)
        self.actionSystem_configuration.setObjectName("actionSystem_configuration")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_17.setText(_translate("MainWindow", "Send"))
        self.pushButton_2.setText(_translate("MainWindow", "Set"))
        self.label_5.setText(_translate("MainWindow", "Injected volume (mL)"))
        self.label.setText(_translate("MainWindow", "Motor 1"))
        self.label_3.setText(_translate("MainWindow", "Speed"))
        self.label_7.setText(_translate("MainWindow", "Injected volume (mL)"))
        self.pushButton_4.setText(_translate("MainWindow", "Set"))
        self.label_8.setText(_translate("MainWindow", "Motor 3"))
        self.label_9.setText(_translate("MainWindow", "Speed"))
        self.pushButton_3.setText(_translate("MainWindow", "Set"))
        self.label_6.setText(_translate("MainWindow", "Injected volume (mL)"))
        self.label_2.setText(_translate("MainWindow", "Motor 2"))
        self.label_4.setText(_translate("MainWindow", "Speed"))
        self.pushButton_5.setText(_translate("MainWindow", "Set"))
        self.label_10.setText(_translate("MainWindow", "Injected volume (mL)"))
        self.label_11.setText(_translate("MainWindow", "Motor41"))
        self.label_12.setText(_translate("MainWindow", "Speed"))
        self.pushButton_6.setText(_translate("MainWindow", "Set"))
        self.label_13.setText(_translate("MainWindow", "Injected volume (mL)"))
        self.label_14.setText(_translate("MainWindow", "Motor 5"))
        self.label_15.setText(_translate("MainWindow", "Speed"))
        self.pushButton_7.setText(_translate("MainWindow", "Set"))
        self.label_16.setText(_translate("MainWindow", "Injected volume (mL)"))
        self.label_17.setText(_translate("MainWindow", "Motor 6"))
        self.label_18.setText(_translate("MainWindow", "Speed"))
        self.pushButton_8.setText(_translate("MainWindow", "Set"))
        self.label_19.setText(_translate("MainWindow", "Injected volume (mL)"))
        self.label_20.setText(_translate("MainWindow", "Motor 7"))
        self.label_21.setText(_translate("MainWindow", "Speed"))
        self.label_22.setText(_translate("MainWindow", "Injected volume (mL)"))
        self.pushButton_9.setText(_translate("MainWindow", "Set"))
        self.label_23.setText(_translate("MainWindow", "Motor 8"))
        self.label_24.setText(_translate("MainWindow", "Speed"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.DC), _translate("MainWindow", "Direct Control"))
        self.pushButton.setText(_translate("MainWindow", "Send"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.SM), _translate("MainWindow", "Serial Monitor"))
        self.pushButton_10.setText(_translate("MainWindow", "Open .csv"))
        self.pushButton_11.setText(_translate("MainWindow", "Send"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.RP), _translate("MainWindow", "Run Protocol"))
        self.label_25.setText(_translate("MainWindow", "Motor 1 Configuration"))
        self.label_27.setText(_translate("MainWindow", "Steps/revolution"))
        self.label_26.setText(_translate("MainWindow", "mL/Steps"))
        self.label_31.setText(_translate("MainWindow", "mL/Steps"))
        self.label_32.setText(_translate("MainWindow", "Steps/revolution"))
        self.label_33.setText(_translate("MainWindow", "Motor 2 Configuration"))
        self.label_40.setText(_translate("MainWindow", "mL/Steps"))
        self.label_42.setText(_translate("MainWindow", "Steps/revolution"))
        self.label_43.setText(_translate("MainWindow", "Motor 5 Configuration"))
        self.label_46.setText(_translate("MainWindow", "Motor 6 Configuration"))
        self.label_44.setText(_translate("MainWindow", "mL/Steps"))
        self.label_45.setText(_translate("MainWindow", "Steps/revolution"))
        self.label_34.setText(_translate("MainWindow", "mL/Steps"))
        self.label_35.setText(_translate("MainWindow", "Steps/revolution"))
        self.label_36.setText(_translate("MainWindow", "Motor 3 Configuration"))
        self.label_37.setText(_translate("MainWindow", "mL/Steps"))
        self.label_38.setText(_translate("MainWindow", "Steps/revolution"))
        self.label_39.setText(_translate("MainWindow", "Motor 4  Configuration"))
        self.label_48.setText(_translate("MainWindow", "Steps/revolution"))
        self.label_47.setText(_translate("MainWindow", "mL/Steps"))
        self.label_49.setText(_translate("MainWindow", "Motor 7 Configuration"))
        self.label_52.setText(_translate("MainWindow", "Motor 8 Configuration"))
        self.label_51.setText(_translate("MainWindow", "Steps/revolution"))
        self.label_50.setText(_translate("MainWindow", "mL/Steps"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.CONFIG), _translate("MainWindow", "Configuration"))
        self.label_41.setText(_translate("MainWindow", "Serial Select"))
        self.actionDirectControl.setText(_translate("MainWindow", "Direct Control"))
        self.actionRunProtocol.setText(_translate("MainWindow", "Run Protocol"))
        self.actionSerial_responses.setText(_translate("MainWindow", "Serial responses"))
        self.actionSystem_configuration.setText(_translate("MainWindow", "System configuration"))

